<a href="https://colab.research.google.com/github/sarwathasan72-svg/Masai_IIT_AIML/blob/main/practiceNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
marks = np.array([40,50,60])
bonus = marks + 5
print(bonus)

zeros_array = np.zeros(5)
print(zeros_array)
ones_array = np.ones(5)
print(ones_array)
numbers = np.arange(1, 11)
print(numbers)
numbers = np.arange(1, 11, 2)
print(numbers)

[45 55 65]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [ ]:
x = np.linspace(-10, 10, 100)
print(x)

In [1]:
import numpy as np

image_2d = np.arange(784).reshape(28, 28)

print(image_2d.shape)
print(image_2d.ndim)
print(image_2d.dtype)
print(image_2d.size)

flat = image_2d.flatten()

print(flat.shape)

(28, 28)
2
int64
784
(784,)


In [10]:
import numpy as np
score = np.array([[30, 20, 100],[50,60,300],[99,98,400]])
#print(score)
zero1=np.zeros(5)
ones10=np.ones(10)
print(ones10)
print(zero1)
shape1 = score.shape
print(shape1)
size1 = score.size
print("Size:", size1)
print("Dimention :" ,score.ndim)
print("data Type :" , score.dtype)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
(3, 3)
Size: 9
Dimention : 2
data Type : int64


In [4]:
#devide range 2-20 in 6 equal parts
import numpy as np
linspace1 = np.linspace(2,10,5)
print(linspace1)
arange1 = np.arange(1,10)
print(arange1)
#range2 = range(0, 1, 0.2)
print(list(range(0, 10, 2)))


[ 2.  4.  6.  8. 10.]
[1 2 3 4 5 6 7 8 9]
[0, 2, 4, 6, 8]


In [23]:
np.random.seed(42)
random_marks = np.random.randint(35, 101)
print(random_marks)


86


In [6]:
import numpy as np
seednum = np.random.seed(42)
seednum. random.randint(35, 101, size=10)
print(seednum)

None


In [5]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])
a[0] = 100
print(a)
a[:3] = 200
print(a)
a[::2] = 300
print(a)
print(a[2:])


[100  20  30  40  50]
[200 200 200  40  50]
[300 200 300  40 300]
[300  40 300]


In [24]:
import numpy as np
b = np.array([[1, 2, 3],
[4, 5, 6],[6,7,8]])
print(b[1:, 0:])
#print(b[0:, 1:])

[[4 5 6]
 [6 7 8]]


In [36]:
Marks = np.array([a,b,c,d,e,f,g],
    [72, 85, 64, 90, 58, 33, 49])
pass_mask = Marks[0][1] >= 50
print('Marks:', Marks)
print('Pass mask:', pass_mask)
print('Passing marks only:', Marks[pass_mask])
Result = np.where(Marks >= 50, 'Pass', 'Fail')
print(Result)

NameError: name 'c' is not defined

In [1]:
import pandas as pd
data = {
    "Name": ["Harsha", "Rahul", "Sneha", "Aman"],
    "Age": [24, 25, 23, 26],
    "Marks": [88, 76, 91, 67]
}

df = pd.DataFrame(data)

df
pd.to_numeric(salary, errors='coerce')

NameError: name 'salary' is not defined

In [ ]:
# A data engineer runs df['dept'].astype(str).str.strip().str.title() . What the result for the entry ' IT ' ? A) 'IT' B) 'It' C) ' IT ' D) 'it'

In [2]:
# In a 500-row dataset, the age column has 80 missing values. Which approach is most appropriate to fill them? A) Drop rows using df.dropna() B) Fill with mean age using df['age'].mean() C) Fill with median age using np.median(df['age'].dropna()) D) Fill with string 'unknown' using df['age'].fillna('unknown')

import numpy as np
b = np.array([[1, 2, 3],
[4, 5, 6],[6,7,8]])
print(b[1:, 0:])
#print(b[0:, 1:])

[[4 5 6]
 [6 7 8]]


In [ ]:
# A data engineer at a fintech startup has received a raw employee payroll DataFrame containing several data quality issues. The task is to write a complete pandas cleaning pipeline that handles missing values, junk characters in the salary column, inconsistent capitalization in the department column, and date parsing — following the strategies for each column type. The cleaned DataFrame must have no remaining null values, correct dtypes, and pass a validation check.

# Constraints & Requirements: Use only pandas and NumPy (import as pd and np ) For categorical string columns with missing values, fill with 'unknown' For numeric columns with missing values, fill with the column's median computed using np.median() on the non-null values For the salary column: remove the ₹ symbol and commas using str.replace(regex=False) , then convert to numeric using pd.to_numeric(errors='coerce') , then fill remaining NaN with the median For the date column: use pd.to_datetime(errors='coerce', dayfirst=True) and fill NaT with pd.to_datetime('1900-01-01') For text columns: apply astype(str).str.strip().str.title() to standardize capitalization After filling the age column's NaN, cast it to int using astype(int) Assemble a clean_df from the individually cleaned columns Validate by printing clean_df.isnull().sum() and calling clean_df.info()

<!-- vccdddsds
sdsdssd -->